export const csvHeader = [
  { label: "Monthly net income", key: "Monthly_net_income" },
  { label: "Property value", key: "Property_value" },

  { label: "insurance expiry", key: "insurance_expiry" },
  { label: "insurance provider", key: "insurance_provider" },
  { label: "insurance type", key: "insurance_type" },
  { label: "mortgage debt", key: "mortgage_debt" },
  { label: "mortgage expiry", key: "mortgage_expiry" },
  { label: "mortgage interest", key: "mortgage_interest" },
  { label: "mortgage provider", key: "mortgage_provider" },
  { label: "mortgage type", key: "mortgage_type" },
  { label: "ownership company number", key: "ownership_company_number" },
  {
    label: "ownership construction date",
    key: "ownership construction date",
  },
  { label: "ownership finish quality", key: "ownership_finish_quality" },
  { label: "ownership internal area", key: "ownership_internal_area" },
  { label: "ownership no of bathroom", key: "ownership_no_of_bathroom" },
  { label: "ownership no of bedroom", key: "ownership_no_of_bedroom" },
  {
    label: "ownership off street parking",
    key: "ownership off street parking",
  },
  { label: "ownership outdoor space", key: "ownership_outdoor_space" },
  { label: "ownership property type", key: "ownership_property_type" },
  { label: "ownership type", key: "ownership_type" },
  { label: "previous estimate", key: "previous_estimate" },
  { label: "previous margin", key: "previous_margin" },
  { label: "property address", key: "property_address" },
  { label: "property estimate", key: "property_estimate" },
  { label: "property id", key: "property_id" },
  { label: "property margin", key: "property_margin" },
  { label: "property name", key: "property_name" },
  { label: "roi gross monthly income", key: "roi_gross_monthly_income" },
  { label: "roi ground rent", key: "roi_ground_rent" },
  { label: "roi management fee", key: "roi_management_fee" },
  { label: "roi mortgage payment", key: "roi_mortgage_payment" },
  {
    label: "roi previous monthly net income",
    key: "roi previous monthly net income",
  },
  { label: "roi service charge", key: "roi_service_charge" },
];
